apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-external-secrets-manager
  namespace: external-secrets
rules:
- apiGroups: ["operator.external-secrets.io"]
  resources: ["operatorconfigs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-logging-manager
  namespace: openshift-logging
rules:
- apiGroups: ["operator.external-secrets.io"]
  resources: ["operatorconfigs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["logging.openshift.io"]
  resources: ["clusterloggings", "clusterlogforwarders"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["generators.external-secrets.io"]
  resources: ["fakes"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-external-logging-manager-binding
  namespace: openshift-logging
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-logging-manager
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-external-secrets-logging-manager-binding
  namespace: external-secrets
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-external-secrets-manager
  apiGroup: rbac.authorization.k8s.io
